### ISSUE TITLE
Screen rotate on Pi 4

### ISSUE THREAD

**Issue by hattoriakuto** [procount/pinn-os#10]
Hi

first off thanks for a wonderful program. I have an issue with the Official Raspberry Pi screen and you program i cant seam to work out how to rotate the screen and I can not find how to get to have pinn-os rotate so that i can use the case for the screen.

any halp and advice is welcome

Thanks in advance

**Comment by procount** [comment]
I think you should be able to do this in config.txt by adding `lcd_rotate=1` (or 2 or 3, depending on how much rotation you need),
See https://www.raspberrypi.org/documentation/configuration/config-txt/video.md. You will also need to configure the rotation in each OS installed by PINN, as each OS is independent.

**Comment by hattoriakuto** [comment]
thanks for that

**Comment by davidstk1311** [comment]
is there no way to "send" the rotation over to the os so you dont have to do it on all os´s individually?

**Comment by procount** [comment]
There is no consistent way of setting the rotation on all OSes.
They could use legacy video drivers, fkms, kms, LCD or some other way of defining the rotation.
Not everyone may want the same rotation on each OS.

You could possibly do this if you cloned the OSes you wanted to install and modified either the tarballs or the partition_setup.sh file, but it's not an ideal solution. OS "flavours" may possibly be an avenue to explore.
