### ISSUE TITLE
Add repo

### ISSUE THREAD

**Issue by sheikhmishar** [procount/pinn-os#16]
I have built PINN installable images for Manjaro KDE, Android Konstakang newer builds and PiKVMv2. Now, I hope it will be helpful to others. How can I share it? Directly create a pull request in this repo?

**Comment by procount** [comment]
Can you provide a URL where they can be accessed from, so I can take a look at them?

**Comment by sheikhmishar** [comment]
Yeah, sure. I have been testing the distros thoroughly for 4 days. Found some issues is partition_setup.sh I copied from previous releases. Now, I fixed all those and everything is mounting properly. TWRP also works. Can you please suggest me a free file hosting site?

**Comment by procount** [comment]
I mainly use sourceforge.net

**Comment by sheikhmishar** [comment]
> I mainly use sourceforge.net

Thank you. Here is the link: https://sourceforge.net/projects/pinn-sheikhmishar/files/

**Comment by sheikhmishar** [comment]
Hello there, is it working?

**Comment by procount** [comment]
Yes it seems to work. Thanks for fixing the partition_setup - Looks like the recovery fstab file has changed.
There are a few issues to fix up for internet download, but I hope to make it available soon.
Thanks.

**Comment by procount** [comment]
I have added Lineage20 & Lineage20-atv
