### ISSUE TITLE
Update lede to 17.01.4

### ISSUE THREAD

**Issue by moham96** [procount/pinn-os#3]
Hi,
can you update lede2Rpi3 to 17.1.04
https://downloads.lede-project.org/releases/17.01.4/targets/brcm2708/bcm2710/lede-17.01.4-brcm2708-bcm2710-rpi-3-ext4-sdcard.img.gz

**Comment by procount** [comment]
Sorry - it looks like I did all the work but forgot to upload the new files to sourceforge 😞. All done now.
