### ISSUE TITLE
Debian64pi4 root password

### ISSUE THREAD

**Issue by Phil995511** [procount/pinn-os#7]
Hello,

I test Debian64pi4 version 2020-01-02 from PINN, what is the root password (or username / password) ?

Regards.

**Comment by procount** [comment]
No idea.
It's sometimes in release_notes.txt but always in os.json.
From PINN, go to maintenance menu, select Debian and opt to change password. Click default and show password and it will be revealed. Cancel if you don't want to change it.

**Comment by Phil995511** [comment]
You are a best man :)

Thank you so much for all !!

**Comment by pwgjr88** [comment]
Hi, I am completely new to PINN, first time using it...
When I go the maintenance menu in PINN (v3.3.4) all I see is "PINN [FIXED]"
I do not see Debian4pi4.
I am sure I am doing something wrong, but don't know what it is...
TIA for your help.

**Comment by procount** [comment]
@pwgjr88 - the maintenance menu is for maintaining OSes you have already installed.

The OSes to install are shown on the Main Menu. You must be connected to the internet for PINN to show the list of available OSes.

Please have a read of README_PINN.md where all the features of PINN are detailed.

**Comment by pwgjr88** [comment]
thanks, I will give the README_PINN.md a read. should have thought of that...
